CREATE TABLE IF NOT EXISTS AUTOR(
    ID_AUTOR INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOME_AUTOR TEXT NOT NULL, 
    COD_AUTOR TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TITULO(
    ID_TITULO INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOME_TITULO TEXT NOT NULL, 
    COD_TITULO TEXT NOT NULL, 
    ID_AUTOR INTEGER NOT NULL,
    FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS EXEMPLAR(
    ID_EXEMPLAR INTEGER PRIMARY KEY AUTOINCREMENT,  
    COD_EXEMPLAR TEXT NOT NULL, 
    ID_TITULO INTEGER NOT NULL,
    FOREIGN KEY(ID_TITULO) REFERENCES TITULO(ID_TITULO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOME_USUARIO TEXT NOT NULL, 
    TEL_USUARIO TEXT, 
    EMAIL_USUARIO TEXT
);

CREATE TABLE IF NOT EXISTS EMPRESTIMO(
    ID_EMPRESTIMO INTEGER PRIMARY KEY AUTOINCREMENT, 
    ID_USUARIO INTEGER NOT NULL, 
    ID_EXEMPLAR INTEGER NOT NULL, 
    DATA_EMPRESTIMO DATE NOT NULL, 
    DATA_DEVOLUCAO DATE NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_EXEMPLAR) REFERENCES EXEMPLAR(ID_EXEMPLAR) ON DELETE CASCADE ON UPDATE CASCADE
);